jwt:
  secret: mySpringProject
  header: Authorization
  expiration: 86400
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: habrpguser
    driver-class-name: org.postgresql.Driver
    password: pgpwd4habr
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml